name = "alx-hackathon-api"
main = "cloudflare-worker.js"
compatibility_date = "2024-03-14"

[[d1_databases]]
binding = "DB"
database_name = "alx_hackathon_db"
database_id = "5d0dcf2a-136e-4ebe-82be-077e64165cd0"
